In [2]:
# NumPy Arrays 
import numpy as np

In [3]:
# 1D NumPy Arrays
lst = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]
arr = np.array(lst)

print(arr * 4)

print(np.mean(arr))

print(np.median(arr))

print(np.std(arr))

print(np.argmin(arr))
print(np.argmax(arr))

# setting min & max index as objects
min_index = np.argmin(arr)
max_index = np.argmax(arr)

print(arr[min_index])
print(arr[max_index])

print(np.min(arr))
print(np.max(arr))
# The outputs from these two codes are the same as those from the previous step

gt_20 = arr[arr>20]
print(gt_20)

[ 80 108  36  48 124  68  16 200 156 140]
24.4
23.5
13.828955130450023
6
7
4
50
4
50
[27 31 50 39 35]


In [4]:
# 2D NumPy Arrays 
matrix = [
    [5, 12, 17, 9],
    [8, 21, 14, 3],
    [6, 13, 19, 11]
]
arr_2 = np.array(matrix)

print(np.shape(arr_2)) # 3 rows and 4 columns

print(arr_2[:, 2])

print(arr_2[1])

print(arr_2 * 2)

print(np.mean(arr_2, axis=0))

print(np.mean(arr_2))

print(np.max(arr_2, axis=1))

print(np.min(arr_2, axis=0))

print(arr_2.flatten())
flat = arr_2.flatten() # Puts as object
print(flat.shape)
# The new shape is 1 row and 12 columns. Flattening the matrix turns the 2D array into a 1D array with all elements ordered by their rows.

print(np.argmin(flat))
print(np.argmax(flat))
argmin = np.argmin(flat)
argmax = np.argmax(flat)

min_coords = np.unravel_index(argmin, arr_2.shape)
max_coords = np.unravel_index(argmax, arr_2.shape)
print(min_coords)
print(max_coords)

print(arr_2[arr_2 > 15])

print(np.sort(arr_2, axis=1))

(3, 4)
[17 14 19]
[ 8 21 14  3]
[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]
[ 6.33333333 15.33333333 16.66666667  7.66666667]
11.5
[17 21 19]
[ 5 12 14  3]
[ 5 12 17  9  8 21 14  3  6 13 19 11]
(12,)
7
5
(np.int64(1), np.int64(3))
(np.int64(1), np.int64(1))
[17 21 19]
[[ 5  9 12 17]
 [ 3  8 14 21]
 [ 6 11 13 19]]


In [5]:
# Prime Star Systems
arr = np.array([
    [2, 3, 5],
    [14, 6, 8],
    [11, 13, 17],
    [7, 10, 13]
])

def num_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n ** 0.5)+1):
        if n % i == 0:
            return False
    return True

def rows_w_prime(arr):
    prime_check = np.vectorize(num_prime)
    rwprime = np.any(prime_check(arr), axis=1)
    return arr[rwprime]

print(rows_w_prime(arr))

[[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]


In [6]:
# Let's Play Checkers!

# 5.1
def board_0():
    return np.zeros((8, 8), dtype=int)

# 5.2 & 5.3
def checkerboard():
    board = np.zeros((8, 8), dtype=int)
    board[::2, ::2] = 1
    board[1::2, 1::2] = 1
    return board

# 5.4
def reverse_checkerboard():
    board = np.zeros((8, 8), dtype=int)
    board[::2, 1::2] = 1
    board[1::2, ::2] = 1
    return board

print(board_0())
print(checkerboard())
print(reverse_checkerboard())

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [8]:
# The Expanding Universe

def expansion(arr, n):
    space = ' ' * n
    expands = [space.join(list(s)) for s in arr]
    return np.array(expands)

universe = np.array(['galaxy', 'clusters'])

print(expansion(universe, 1))
print(expansion(universe, 4))

['g a l a x y' 'c l u s t e r s']
['g    a    l    a    x    y' 'c    l    u    s    t    e    r    s']


In [20]:
# Second-Brightest Star

def secondDimmest(stars):
    sorted_stars = np.sort(stars, axis=1)
    return sorted_stars[:, -2]

np.random.seed(123)
stars = np.random.randint(500, 2000, (5, 5))

print(stars)

print(secondDimmest(stars))

[[1889 1906 1846 1622 1541]
 [ 606 1647 1738  596  613]
 [1138  547  573 1442  724]
 [ 611 1933 1863 1346 1777]
 [ 920 1108 1732 1592  951]]
[1889 1647 1138 1863 1592]
